version: "2.4"
services:

  # -------------------------------------
  # Spanner Emulator
  # -------------------------------------

  emu:
    image: gcr.io/cloud-spanner-emulator/emulator
    container_name: spanner_emulator
    # volumes:
    #   - 
    ports:
      - 9010:9010  # gRPC
      - 9020:9020  # REST
    # entrypoint:
    #   ["start"]

  consumer:
    extends:
      file: docker-compose-base.yml
      service: spanner-consumer
    environment:
      # consumer settings
      CONSUMER_NAME: 'SPANNER-TEST'
      TENANCY_HEADER: x-oauth-realm
      # emulator and remote account settings
      SERVICE_ACCOUNT: ${SERVICE_ACCOUNT:-}
      SPANNER_EMULATOR_HOST: emu:9010
      # redis
      REDIS_PASSWORD: password
      # kafka settings
      KAFKA_CONFIG_PATH: /code/conf/consumer/kafka.json
      KAFKA_URL: ${KAFKA_URL}
      SECURITY.PROTOCOL: SASL_SSL
      SASL.MECHANISM: PLAIN
      SASL.USERNAME: ${KAFKA_SASL_USERNAME}
      SASL.PASSWORD: ${KAFKA_SASL_PASSWORD}

  redis:
    image: redis:alpine
    command: >
      redis-server
      --requirepass password
