version: "2.4"
services:

  consumer:
    extends:
      file: docker-compose-base.yml
      service: spanner-consumer
    environment:
      # consumer settings
      CONSUMER_NAME: 'SPANNER-TEST'
      TENANCY_HEADER: x-oauth-realm
      EXPOSE_PORT: 9013
      # emulator and remove account settings
      SERVICE_ACCOUNT: ${SERVICE_ACCOUNT:-}
      SPANNER_EMULATOR_HOST: emu:9010
      # redis
      REDIS_PASSWORD: password
      REDIS_DB: 0
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # kafka settings
      KAFKA_CONFIG_PATH: /code/conf/consumer/kafka.json
      KAFKA_URL: ${KAFKA_URL}
      SECURITY.PROTOCOL: SASL_SSL
      SASL.MECHANISM: PLAIN
      SASL.USERNAME: ${KAFKA_SASL_USERNAME}
      SASL.PASSWORD: ${KAFKA_SASL_PASSWORD}
    ports:
      - 9013:9013
  redis:
    image: redis:alpine
    command: >
      redis-server
      --requirepass password
      --appendonly yes
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
